services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: microservicesdb
      POSTGRES_USER: microservices_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
