server:
  port: 8080

spring:
  application:
    name: microservices-application
  datasource:
    url: jdbc:postgresql://localhost:5438/microservicesdb
    username: microservices_user
    password: secret_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n%ex"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
